/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerGuidanceResponse {
  'matches' : Array<JobMatchResult>,
  'response' : string,
}
export interface Job {
  'title' : string,
  'growthOutlook' : string,
  'requiredInterests' : Array<string>,
  'description' : string,
  'salaryRange' : string,
  'requiredSkills' : Array<string>,
}
export interface JobMatchResult { 'job' : Job, 'score' : bigint }
export interface Message { 'content' : string, 'role' : string }
export interface UserProfile {
  'bio' : string,
  'interests' : Array<string>,
  'name' : string,
  'role' : UserRole,
  'workStylePreferences' : Array<string>,
  'personalityTraits' : Array<string>,
  'skills' : Array<string>,
}
export type UserRole = { 'employee' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJob' : ActorMethod<[Job], undefined>,
  'addMessage' : ActorMethod<[Message], CareerGuidanceResponse>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createUserProfile' : ActorMethod<[string, UserRole, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConversationHistory' : ActorMethod<[], Array<Message>>,
  'getJob' : ActorMethod<[string], Job>,
  'getJobList' : ActorMethod<[], Array<Job>>,
  'getMatchingJobs' : ActorMethod<[], Array<JobMatchResult>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedJobs' : ActorMethod<[], undefined>,
  'updateUserProfile' : ActorMethod<
    [Array<string>, Array<string>, Array<string>, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];