/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Job = IDL.Record({
  'title' : IDL.Text,
  'growthOutlook' : IDL.Text,
  'requiredInterests' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
export const JobMatchResult = IDL.Record({ 'job' : Job, 'score' : IDL.Nat });
export const CareerGuidanceResponse = IDL.Record({
  'matches' : IDL.Vec(JobMatchResult),
  'response' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'employee' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'workStylePreferences' : IDL.Vec(IDL.Text),
  'personalityTraits' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJob' : IDL.Func([Job], [], []),
  'addMessage' : IDL.Func([Message], [CareerGuidanceResponse], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, UserRole, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getJob' : IDL.Func([IDL.Text], [Job], ['query']),
  'getJobList' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getMatchingJobs' : IDL.Func([], [IDL.Vec(JobMatchResult)], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedJobs' : IDL.Func([], [], []),
  'updateUserProfile' : IDL.Func(
      [
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Job = IDL.Record({
    'title' : IDL.Text,
    'growthOutlook' : IDL.Text,
    'requiredInterests' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const JobMatchResult = IDL.Record({ 'job' : Job, 'score' : IDL.Nat });
  const CareerGuidanceResponse = IDL.Record({
    'matches' : IDL.Vec(JobMatchResult),
    'response' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'workStylePreferences' : IDL.Vec(IDL.Text),
    'personalityTraits' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJob' : IDL.Func([Job], [], []),
    'addMessage' : IDL.Func([Message], [CareerGuidanceResponse], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, UserRole, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getJob' : IDL.Func([IDL.Text], [Job], ['query']),
    'getJobList' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getMatchingJobs' : IDL.Func([], [IDL.Vec(JobMatchResult)], []),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedJobs' : IDL.Func([], [], []),
    'updateUserProfile' : IDL.Func(
        [
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };